#--------------------------------------------------------
#Hej, tu skript "G-Chat", wykonany przez Hiperk'a ;)
#--------------------------------------------------------
#
#-----------------------[Permisje]-----------------------
#
# 1.chat.admin.on | 2.chat.admin.off | 3.chat.admin.cc
# 3.chat.say | 4.chat.vip.bb | 5.chat.vip.bb.only
# 6.chat.slowmode | 7.chat.admin.slowmode.toogle
# 8.chat.admin.automsg.toogle | 9.chat.admin.reload
#
#--------------------------------------------------------
# Tag - Ustaw tag który będzie wyświetlny przy funkcjach
# Takich jak: cc/off/on
tag: '&f&l[&aEX&bCORE&f&l]'
#--------------------------------------------------------
# TAG.AutoMsg - Ustawia tag dla automessage
# Np. &f[&aInfo&f]
# Będzie wyświetlane przed każda wiadomością
TAG.AutoMsg: '&f&l[&aInfo&f&l]'
#--------------------------------------------------------
# TAG.Active - Jeśli ustawisz na true
# Będzie wystietlat prefiks który ustaliłeś powyżej
# True=Właczone False=Wyłączone
TAG.Active: false
#--------------------------------------------------------
# Slowmode.time - Co ile czasu gracz moze pisać na czacie
# Domyślnie jest na 3s
Slowmode.time: '3'
#--------------------------------------------------------
# Slowmode.Active - Włacza slowmode na czaie
# Powysze ustawienie pazwala na ustalenie
# Co ile można pisąć na czacie
# Możnna włączyć i wyłączyć komenda /chat slowmode
# Domyślnie wyłączone
# Permisje -> chat.admin.slowmode.toggle
# Pemisje aby admin nie musiał czekać -> chat.slowmode
# True=Właczone False=Wyłączone
Slowmode.Active: false
#--------------------------------------------------------
# AutoMSG.Time - Co jaki czas wyświela ogłoszenia
# Dosępne czasy: 1=10s 2=15 3=20s 4=30s
# Każdy inny numerek nie będzie działał
AutoMSG.Time: 2
#--------------------------------------------------------
# AutoMSG.Active - Włacza i wyłacza automessage na czacie
# Można właczyć i wyłączyć komenda /chat automsg
# Domyślnie jest wyłączone
# Permisje -> chat.admin.automsg.toggle
# True=Właczone False=Wyłączone
AutoMSG.Active: false
#--------------------------------------------------------
# Automsg - Pozwala na dostosowanie wiadomosci
# Które są wyświetlanie na czacie
# Wysłanie wiadomości jest domyślnie co 15s
# Dodawanie nowych wiadomosci:
# 4: 'Dowolny tekst' | I tak ciągle.
automsg:
  1: '&2Ustaw wiadomosc automessage &c/plugins/G-Chat/config.yml'
  2: '&4Ustaw wiadomosc automessage &c/plugins/G-Chat/config.yml'
  3: '&eUstaw wiadomosc automessage &c/plugins/G-Chat/config.yml'
#--------------------------------------------------------
# BB.Cast.Active - Włacza i Wyłacza komende /chat bb
# BBCast pozwala na pisanie ogłoszeń co 5 min
# Czas można zmienić w configu
# True=Właczone False=Wyłączone
BB.Cast.Active: false
#--------------------------------------------------------
# BB.Cast.message - Pozwala dostosować wygląd Ogłoszeń
# Zmienna: (nick) zostanie podmieniona na np. Kowalski
# Zmienna: (tersc) zostanie podmieniona na tresc
# Którą Kowalski wpisze na czacie /chat bb <tresc>
BB.Cast.message: '&e&l[&a&lBBCore&e&l]&a[&e(nick)&a] &7(tresc)'
#--------------------------------------------------------
