#--------------------------------------------------------
#Hej, tu skript "G-Chat", wykonany przez Hiperk'a ;)
#--------------------------------------------------------
#
#-----------------------[Permisje]-----------------------
#
# 1.chat.admin.on | 2.chat.admin.off | 3.chat.admin.cc
# 3.chat.say | 4.chat.vip.bb | 5.chat.vip.bb.only
# 6.chat.slowmode | 7.chat.admin.slowmode.toogle
# 8.chat.admin.automsg.toogle | 9.chat.admin.reload
#
#--------------------------------------------------------
# AutoUpdate.Enable - Jeśli ustawisz na true będziesz
# Dostawał automatycznie najnowsze akutulizacje.
AutoUpdate.Enable: false
#--------------------------------------------------------
# Tag - Ustaw tag który będzie wyświetlny przy funkcjach
# Takich jak: cc/off/on
tag: '                     &e&l<&3EX&aCORE&e&l>'
#--------------------------------------------------------
# TAG.AutoMsg - Ustawia tag dla automessage
# Np. &f[&aInfo&f]
# Będzie wyświetlane przed każda wiadomością
TAG.AutoMsg: '&f&l[&aInfo&f&l]'
#--------------------------------------------------------
# TAG.Enable - Jeśli ustawisz na true
# Będzie wystietlat prefiks który ustaliłeś powyżej
# True=Właczone False=Wyłączone
TAG.Enable: false
#--------------------------------------------------------
# Slowmode.time - Co ile czasu gracz moze pisać na czacie
# Domyślnie jest na 3s
Slowmode.time: '3'
#--------------------------------------------------------
# Slowmode.Enable - Włacza slowmode na czaie
# Powysze ustawienie pazwala na ustalenie
# Co ile można pisąć na czacie
# Możnna włączyć i wyłączyć komenda /chat slowmode
# Domyślnie wyłączone
# Permisje -> chat.admin.slowmode.toggle
# Pemisje aby admin nie musiał czekać -> chat.slowmode
# True=Właczone False=Wyłączone
Slowmode.Enable: false
#--------------------------------------------------------
# AutoMSG.Time - Co ustalony czas wyświela ogłoszenia
# Czas ustawiamy tylko w sekundach
# Domyślnie jest co 10s
AutoMSG.Time:  10
#--------------------------------------------------------
# AutoMSG.Enable - Włacza i wyłacza automessage na czacie
# Można właczyć i wyłączyć komenda /chat automsg
# Domyślnie jest wyłączone
# Permisje -> chat.admin.automsg.toggle
# True=Właczone False=Wyłączone
AutoMSG.Enable: false
#--------------------------------------------------------
# Automsg - Pozwala na dostosowanie wiadomosci
# Które są wyświetlanie na czacie
# Wysłanie wiadomości jest domyślnie co 15s
# Dodawanie nowych wiadomosci:
# 4: 'Dowolny tekst' | I tak ciągle.
automsg:
  1: 
    cast:
    - '&7==============( &c#Info &7)=============='
    - '&2Ustaw wiadomosc automessage &c/plugins/G-Chat/config.yml'
  2:
    cast:
    - '&7==============( &e#Info &7)=============='
    - '&4Ustaw wiadomosc automessage &c/plugins/G-Chat/config.yml'
  3:
    cast:
    - '&7==============( &d#Info &7)=============='
    - '&eUstaw wiadomosc automessage &c/plugins/G-Chat/config.yml'
#--------------------------------------------------------
# BB.Cast.Enable - Włacza i Wyłacza komende /chat bb
# BBCast pozwala na pisanie ogłoszeń co 5 min
# Czas można zmienić w configu
# True=Właczone False=Wyłączone
BB.Cast.Enable: true
#--------------------------------------------------------
# BB.Cast.Time - Co ile czasu gracz moze uzyc komendy.
# Możemy ustawić tylko liczby.
# Liczby są podane w sekundach
# Domyślnie jest 10s.
BB.Cast.Time: 10
#--------------------------------------------------------
# BB.Cast.message - Pozwala dostosować wygląd Ogłoszeń
# Zmienna: (nick) zostanie podmieniona na np. Kowalski
# Zmienna: (tersc) zostanie podmieniona na tresc
# Którą Kowalski wpisze na czacie /chat bb <tresc>
BB.Cast.message: '&e&l[&a&lBBCore&e&l]&a[&e(nick)&a] &7(tresc)'
#--------------------------------------------------------
# Chat.view.on - Pozwala na dowolne skonfigurowanie
# Czatu pod swoj serwer
# Dozwolone zmienne: (nick), (tag)
Chat.view.on:
- ' '
- '(tag)'
- ' '
- '&9> &aChat zostal wlaczony przez &7(nick)'
- ' '
- ' '
#--------------------------------------------------------
# Chat.view.off - Pozwala na dowolne skonfigurowanie
# Czatu pod swoj serwer
# Dozwolone zmienne: (nick), (tag)
Chat.view.off:
- ' '
- '(tag)'
- ' '
- '&9> &aChat zostal wylaczony przez &7(nick)'
- ' '
- ' '
#--------------------------------------------------------
# Chat.view.reson - Pozwala na dowolne skonfigurowanie
# Czatu pod swoj serwer
# Dozwolone zmienne: (nick), (tresc), (tag)
Chat.view.reson:
- ' '
- '(tag)'
- ' '
- '&9> &aChat zostal wylaczony przez &7(nick)'
- '&9> &aPowód: &c(tresc)'
- ' '
#--------------------------------------------------------
# Chat.view.cc - Pozwala na dowolne skonfigurowanie
# Czatu pod swoj serwer
# Dozwolone zmienne: (nick), (tag)
Chat.view.cc: 
- '&9> &aChat zostal wyczyszczony przez &7(nick)'
#--------------------------------------------------------
